image:
  - Visual Studio 2022
environment:
  matrix:
    - PYTHON: "C:\\PYTHON36"
    - PYTHON: "C:\\PYTHON37"
    - PYTHON: "C:\\PYTHON38"
    - PYTHON: "C:\\PYTHON39"
    - PYTHON: "C:\\PYTHON310"
    - PYTHON: "C:\\PYTHON311"
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip setuptools wheel"
  - "%PYTHON%\\python.exe -m pip install --upgrade Pillow"
  - "%PYTHON%\\python.exe -m pip install codecov coverage nose pynput babel"
  - "%PYTHON%\\python.exe -c 'import babel; print(babel.__version__)'"
build: off
test_script:
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m nose --with-coverage"
after_test:
  - "%PYTHON%\\Scripts\\codecov.exe"
