image:
  - Visual Studio 2022
environment:
  matrix:
    - PYTHON: "C:\\PYTHON34"
    - PYTHON: "C:\\PYTHON35"
    - PYTHON: "C:\\PYTHON36"
    - PYTHON: "C:\\PYTHON37"
    - PYTHON: "C:\\PYTHON38"
    - PYTHON: "C:\\PYTHON39"
    - PYTHON: "C:\\PYTHON310"
    - PYTHON: "C:\\PYTHON311"
install:
  - "%PYTHON%\\python.exe -m pip install --upgrade pip"
  - "%PYTHON%\\python.exe -m pip install zlib codecov coverage nose pillow pynput babel"
build: off
test_script:
  - "%PYTHON%\\python.exe -m pip install ."
  - "%PYTHON%\\python.exe -m nose --with-coverage"
after_test:
  - "%PYTHON%\\Scripts\\codecov.exe"
