coverage:
  ci:
    - travis
    - appveyor
  status:
    patch: false
    changes: false
    project:
      default:
        target: '80'
  ignore:
    - "babel"
    - "ctypes"
    - "pynput"
    - "pytz"
comment: false
